apiVersion: batch/v1
kind: Job 
metadata:
  name: testbwa
spec:
  template:
    metadata:
      name: testbwa
    spec:
      containers:
      - name: hello 
        image: memoryzpp/buildfalcon3 #local docker images 
        imagePullPolicy: IfNotPresent #it first look for local images
        volumeMounts:  #container volumes
        - mountPath: /fastq 
          name: fastq-volume
        - mountPath: /ref
          name: ref-volume
        command: ["sh"]
        args: ["/bwa.sh"]
      volumes:  
      - name: fastq-volume
        hostPath:  #path in the host machine
          path: /pool/storage/fastq
      - name: ref-volume
        hostPath:
          path: /local/ref
      nodeSelector:
        devicetype: merlin3
      restartPolicy: Never
