##################################################################
#          Falcon Accelerated Genomics Image v1.0.1              #
#                                                                #
#  The Falcon Accelerated Genomics Data Analysis Solutions       #
#  comprising the fcs-genome software allows for variant         #
#  calling for both germline and somatic mutations based on the  #
#  GATK Best Practices pipelines. The performance of the         #
#  pipelines is significantly improved with Falcon's             #
#  acceleration technologies.                                    #
#                                                                #
#  USAGE:                                                        #
#  - Software package is installed in: /usr/local/falcon         #
#  - Image initialization: /root/setup.sh                        #
#  - Example scripts: /usr/local/falcon/example-wgs-germline.sh  #
#                                                                #
#  For questions, please contact: support@falcon-computing.com   #
##################################################################
